apiVersion: v1
kind: ConfigMap
metadata:
  name: manager-config
  namespace: md5-cracker
data:
  TASK_SIZE: "100000"
  MONGO_URI: "mongodb://mongodb-0.mongodb-headless.md5-cracker.svc.cluster.local:27017/md5_cracker?directConnection=true"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"