apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: md5-cracker
data:
  rabbitmq.conf: |
    default_queue_type = classic
    prometheus.return_per_object_metrics = true
  enabled_plugins: |
    [rabbitmq_management, rabbitmq_prometheus].